### ISSUE TITLE
"NameError: 'syn' is not defined" occuring in examples 1, 2 and 3

### ISSUE THREAD

**Issue by NinaOmejc** [LFPy/tutorial_at_EBRAINS#1]
Hi, first thank you for the nice set of examples and exercises. I've run them on ebrains, where it works, but now I installed the LFPy and NEURON locally and I'm having issues while trying to run the same examples, from 1 to 3. 

The error is in line with the synapse declaration:
```
synapse = LFPy.Synapse(...) 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 2, in <module>
  File "D:\Learning\lfpy\venv\lib\site-packages\LFPy\pointprocess.py", line 126, in __init__
    self.hocidx = int(cell.set_synapse(idx=idx, syntype=syntype,
  File "D:\Learning\lfpy\venv\lib\site-packages\LFPy\cell.py", line 586, in set_synapse
    self.synlist.append(syn)
NameError: name 'syn' is not defined. Did you mean: 'sys'?
```

Can you help me resolve the issue? 
Thank you.

**Comment by espenhgn** [comment]
Hi. How did you install LFPy locally? 
The breaking code doesn't exist anymore in the more recent versions (i.e., LFPy-2.3.2). 
Can you force a reinstall, i.e., with `pip install --upgrade LFPy`, and see if this fixes the issue?

Also, I should clarify, LFPy on Windows is on our end a fairly uncharted territory. It's mainly developed on Mac/Linux OS.

**Comment by NinaOmejc** [comment]
Hi,
thank you for a quick reply! 
Yeah, okay, then maybe it's because of Windows. 

Otherwise, I have python3.10.11 and I installed the lfpy using pip, installed NEURON from binary and added its path to the environment. But it seems it installed lfpy version 2.1. When I tried to upgrade it, I got an error saying that the requirement neuron>=7.7 is not satisfied. However, when I import neuron and check the version, it says its the newest, 8.2.6+.

Any thoughts or should I just try with Linux?

**Comment by espenhgn** [comment]
Ok, this leaves some options:
- continue to use EBRAINS or other cloud-like service such as https://colab.research.google.com
- Running via Docker may be a good option, see https://lfpy.readthedocs.io/en/latest/readme.html#docker. The corresponding [Dockerfile](https://github.com/LFPy/LFPy/blob/master/Dockerfile) may require some minor updates to Ubuntu package versions specified therein. 
- Try and fix the above issue on Windows, which I can't replicate. There are no working Windows builds on https://pypi.org/project/NEURON/ either, so the version check when installing LFPy may fail in mysterious ways if the reported version is indeed "8.2.6+"
